name: provenance

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  verify-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip xxd
          pip3 install opentimestamps-client
      - name: Generate manifest
        run: |
          python3 scripts/gen_provenance.py
      - name: Verify (best effort)
        run: |
          if [ -f proofs/merkle_root.bin ]; then
            ots verify proofs/merkle_root.bin || true
          fi
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: provenance
          path: |
            provenance.json
            provenance.json.asc
            proofs/**
